### ISSUE TITLE
Alternative source

### ISSUE THREAD

**Issue by cehsu** [voteliquid/sf-legislation#5]
Could scraping this site be used in addition to or instead of meeting minutes? https://sfgov.legistar.com/PersonDetail.aspx?ID=36813&GUID=FADDCE79-BAFF-44FD-AA37-43669F93C834&Search=

**Comment by dsernst** [comment]
Sorry didn't see this until now (wasn't watching this repo, oops). 🌚 

--------------

Last week you showed me a Google Sheet of votes by reps. I'm guessing you used this site but how exactly did you get it?

**Comment by dsernst** [comment]
Relevant to https://github.com/liquidvote/liquid-api/issues/18

**Comment by dsernst** [comment]
I'm going to close this issue for now. 

The answer (per the work in https://github.com/liquidvote/scripts/pull/3) is 👍 yes, legistar is also useful, especially for scraping the legislators' votes on individual items.
